### ISSUE TITLE
make manifests & make generate do a nil pointer

### ISSUE THREAD

**Issue by elee1766** [kluctl/template-controller#85]
trying on the current main branch 
```
λ ~/re/github./ele/template-controller make manifests                                                                                           main [1824]
test -s /home/a/repo/github.com/elee1766/template-controller/bin/controller-gen || GOBIN=/home/a/repo/github.com/elee1766/template-controller/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.9.2
/home/a/repo/github.com/elee1766/template-controller/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa010de]

goroutine 142 [running]:
go/types.(*Checker).handleBailout(0xc000878e00, 0xc000d51d40)
        /home/a/.asdf/installs/golang/1.22.0/go/src/go/types/check.go:367 +0x88
panic({0xbb2600?, 0x1292d00?})
        /home/a/.asdf/installs/golang/1.22.0/go/src/runtime/panic.go:770 +0x132
go/types.(*StdSizes).Sizeof(0x0, {0xda5698, 0x129b540})
        /home/a/.asdf/installs/golang/1.22.0/go/src/go/types/sizes.go:228 +0x31e
go/types.(*Config).sizeof(...)
        /home/a/.asdf/installs/golang/1.22.0/go/src/go/types/sizes.go:333
go/types.representableConst.func1({0xda5698?, 0x129b540?})
        /home/a/.asdf/installs/golang/1.22.0/go/src/go/types/const.go:76 +0x9e
go/types.representableConst({0xdab9d8, 0x12675a0}, 0xc000878e00, 0x129b540, 0xc000d514b0)
        /home/a/.asdf/installs/golang/1.22.0/go/src/go/types/const.go:92 +0x192
go/types.(*Checker).representation(0xc000878e00, 0xc00092ad00, 0x129b540)
        /home/a/.asdf/installs/golang/1.22.0/go/src/go/types/const.go:256 +0x65
go/types.(*Checker).implicitTypeAndValue(0xc000878e00, 0xc00092ad00, {0xda56c0, 0xc0032963f0})
        /home/a/.asdf/installs/golang/1.22.0/go/src/go/types/expr.go:375 +0x30d
go/types.(*Checker).assignment(0xc000878e00, 0xc00092ad00, {0xda56c0, 0xc0032963f0}, {0xc7df7c, 0x14})
        /home/a/.asdf/installs/golang/1.22.0/go/src/go/types/assignments.go:52 +0x2e5
go/types.(*Checker).initConst(0xc000878e00, 0xc00169d380, 0xc00092ad00)
        /home/a/.asdf/installs/golang/1.22.0/go/src/go/types/assignments.go:126 +0x336
go/types.(*Checker).constDecl(0xc000878e00, 0xc00169d380, {0xda82f0, 0xc000702160}, {0xda82f0, 0xc000702180}, 0x0)
        /home/a/.asdf/installs/golang/1.22.0/go/src/go/types/decl.go:490 +0x348
go/types.(*Checker).objDecl(0xc000878e00, {0xdb1018, 0xc00169d380}, 0x0)
        /home/a/.asdf/installs/golang/1.22.0/go/src/go/types/decl.go:191 +0xa49
go/types.(*Checker).packageObjects(0xc000878e00)
        /home/a/.asdf/installs/golang/1.22.0/go/src/go/types/resolver.go:693 +0x4dd
go/types.(*Checker).checkFiles(0xc000878e00, {0xc00068e570, 0x5, 0x5})
        /home/a/.asdf/installs/golang/1.22.0/go/src/go/types/check.go:408 +0x1a5
go/types.(*Checker).Files(...)
        /home/a/.asdf/installs/golang/1.22.0/go/src/go/types/check.go:372
sigs.k8s.io/controller-tools/pkg/loader.(*loader).typeCheck(0xc00039d0e0, 0xc0003a9740)
        /home/a/.asdf/installs/golang/1.22.0/packages/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/loader/loader.go:286 +0x36a
sigs.k8s.io/controller-tools/pkg/loader.(*Package).NeedTypesInfo(0xc0003a9740)
        /home/a/.asdf/installs/golang/1.22.0/packages/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/loader/loader.go:99 +0x39
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check(0xc001ccf9e0, 0xc0003a9740)
        /home/a/.asdf/installs/golang/1.22.0/packages/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/loader/refs.go:268 +0x2b7
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check.func1(0x51?)
        /home/a/.asdf/installs/golang/1.22.0/packages/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/loader/refs.go:262 +0x53
created by sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check in goroutine 133
        /home/a/.asdf/installs/golang/1.22.0/packages/pkg/mod/sigs.k8s.io/controller-tools@v0.9.2/pkg/loader/refs.go:260 +0x1c5
```
i've tried on both go 1.21.3 and 1.22

fresh clone, linux x86

am i doing something wrong ?

**Comment by codablock** [comment]
@elee1766 Can you retry with the latest main version? I was able to reproduce the crash in a docker container (I'm using Mac and it didn't crash outside of docker) and upgrading controler-gen solved the crash for me.

**Comment by elee1766** [comment]
seems good now! closing.
